default:
  image: node:lts
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  before_script:
    - npm i -g npm@latest
    - test -d node_modules || npm ci

include:
  template: Dependency-Scanning.gitlab-ci.yml

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - lib/

lint:
  stage: test
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
