name: Main
on:
  - push
  - pull_request
jobs:
  test:
    name: Build script
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install npm@7
        run: npm install -g npm@latest
      - name: Install script dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test
